spring:
 profiles:
    active: dev
---
server:
  port: 7001
spring:
  application:
    name: microservicecloud-eureka-config-client
    profiles: dev
eureka:
  instance:
    hostname: eureka-config7001.com
  client:
    register-with-eureka: false
    fetch-registry: false 
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka
 
---  
server:
  port: 7002      
spring:
  application:
    name: microservicecloud-eureka-config-client
    profiles: test
eureka:
  instance:
    hostname: eureka-config7002.com
  client:
    register-with-eureka: false
    fetch-registry: false 
    service-url:
     defaultZone: http://eureka7002.com:7002/eureka
