spring:
 profiles:
    active: dev
---
server:
  port: 8201
spring:
  application:
    name: microservicecloud-config-client
    profiles: dev
    application:
          name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka
 
---  
server:
  port: 8202      
spring:
  application:
    name: microservicecloud-config-client
    profiles: test
    application:
          name: microservicecloud-config-client  
eureka:
  client: 
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka
           